### ISSUE TITLE
Deploy frontend github pages

### ISSUE THREAD

**Issue by Denperidge** [osoc22/project-idlab#11]
I can get this working for sure!

- [x] Docs viewable on GitHub Pages
- [x] App viewable on GitHub Pages(?)
- [x] Modify the app to allow for non-locally-hosted pods & interfaces
- [x] Research whether automated build & deploy is possible (considering Parcel)
- [x] Have a navigation/landing page to the web app and the docs

**Comment by DemianD** [comment]
This might be interesting: https://github.blog/changelog/2021-12-16-github-pages-using-github-actions-for-builds-and-deployments-for-public-repositories/

It's a blog post that contains a new (official) GitHub Action called "deploy-pages", to automatically deploy on push

**Comment by Denperidge** [comment]
Automation through GitHub will hopefully be a go through #13
