### ISSUE TITLE
Document how to try the Solid login

### ISSUE THREAD

**Issue by th0rgall** [osoc22/project-idlab#19]
Imagine that a developer visits https://osoc22.github.io/project-idlab/app/ without seeing the readme first, how can they get started with the app?

They need a Pod URL and WebID, it would be good to include some info on how to get those two things. Ideally with some pointers on that page!

Either...
- Link to this page https://solidproject.org/users/get-a-pod
- Update the ./run.sh script so it automatically makes a pod with a test webID, and mention this in the docs.

**Comment by Denperidge** [comment]
The ./run.sh is already the case, but could indeed be clearer! Will update the docs and interfaces to be more compliant with this
