### ISSUE TITLE
Create an Event interface to SolidDataset

### ISSUE THREAD

**Issue by DemianD** [osoc22/project-idlab#20]
Add all the CRUD operations to read calendar events from a pod, and write events to a pod.

Interface with one single SolidDataset if it doesn't exist yet.

- [x] basic handling of a dataset

- [x] createEvent(): should take JSON-LD, returns the event with a new ID => figure out how to create an ID (maybe it's just a part of the Thing API? When you create a Thing?). Look into a UUIDv4 generator if nothing is built-in.
- [x] updateEvent(id, content)
- [x] getAllEvents(): should produce JSON-LD

**Comment by th0rgall** [comment]
Cat did:

Through JS, we now can:
- Create, save & update Things of any type
- Create, save & update Events (currently iCal, but can/will be changed?)
- Create a dataset
- List all things from the dataset

You can test it all out by just running tester() in your console window and checking the changes through either listThingsFromDataset() or https://otto-aa.github.io/solid-filemanager/

**Comment by Denperidge** [comment]
@th0rgall do we consider the issue closed/succeeded? Since it technically doesn't take json-ld, but it will be easy to implement (and imo having it take javascript arguments makes it more versatile than straight json-ld

**Comment by Denperidge** [comment]
Added delete as well, closing this until further notice!
