### ISSUE TITLE
Integrate a calendar in the Svelte app (optional)

### ISSUE THREAD

**Issue by DemianD** [osoc22/project-idlab#24]
#3 is about finding a good calendar framework to use in our Svelte app. When a decision is made, we can start adding it.

It should be possible to add calendar data to it (persisted in the Solid pod #20).

Open question: in what format are we going to represent the calendar events? Linked Data or plain JSON?

Option: https://fullcalendar.io/

**Comment by th0rgall** [comment]
We decided to have a more simplified calendar that is manually built in the design https://whimsical.com/powerful-data-GUJq5UmEZ5eQ7cHYQ74QFV (based on the Svelte UI we already had).
