### ISSUE TITLE
Ability to change your pod location

### ISSUE THREAD

**Issue by th0rgall** [osoc22/project-idlab#26]
Ben:
> He said it would a really nice idea for the demo to showcase how you can easily change your pod from Inrupt to SolidCommunity to localhost to show how easy it is to use your* linked data.

Open question: should we create a feature that helps you move (upload) your data, given a source pod URL and target pod URL?

Or just create docs on how to do this with CLI and be able to demo it?

**Comment by Denperidge** [comment]
I'll be dropping some links that might be worth checking out
- https://github.com/pdsinterop/solid-migrator
- https://github.com/pdsinterop/solid-migrator-app

**Comment by Denperidge** [comment]
Close for out of scope
