### ISSUE TITLE
Find a framework for rendering calendars (optional)

### ISSUE THREAD

**Issue by th0rgall** [osoc22/project-idlab#3]
Find a library for rendering a calendar

Minimal alternative: just render scheduled events below each other like now, indicating their time. No traditional calendar view.

**Comment by Denperidge** [comment]
(Duplicated relevant info from our Calendar research file)

https://fullcalendar.io/docs → not fully open source, react based
https://github.com/nhn/tui.calendar → open source, vanilla/react/vue
https://github.com/6eDesign/svelte-calendar → open source, svelte based
https://github.com/mattlewis92/angular-calendar → open source, angular based

**Comment by DemianD** [comment]
Full Calendar for Svelte: https://github.com/YogliB/svelte-fullcalendar

**Comment by Denperidge** [comment]
@yustarandomname is this issue deprecated?
