### ISSUE TITLE
Create RDF/JSON-LD data model for events

### ISSUE THREAD

**Issue by th0rgall** [osoc22/project-idlab#47]
### RDF Data model of an "Event"
Each calendar event is a "Thing", that follows the schema.org vocabulary
- the thing has a start time and end time
- it has a title
- ..

**Comment by th0rgall** [comment]
Matei's proposal: https://tinyurl.com/3yykwu4a

**Comment by Denperidge** [comment]
Is there a specific reason/place we'd need this? We follow the shema.org/Event fully until now.

**Comment by Matei9721** [comment]
@Denperidge I think this can be closed now. It was before we went with the Inrupt + schema.org combo
