### ISSUE TITLE
Integrate solid data with the frontend

### ISSUE THREAD

**Issue by th0rgall** [osoc22/project-idlab#48]
Integrate #20 with #46

**Comment by Denperidge** [comment]
Now that #50 is finishing up, this shall be my task tomorrow!

**Comment by Denperidge** [comment]
Now that https://github.com/osoc22/project-idlab/pull/50 is finishing up, this shall be my task tomorrow!

**Comment by Denperidge** [comment]
(Renamed the issue as #20 and #46  are concerning the programming interface and the UI, not the weather, hence I did the 50 assigns and unassigns because I also confused myself)

**Comment by Matei9721** [comment]
Blocked by #71 and #72 .

**Comment by Denperidge** [comment]
Linked to #71 and fixed by #77
