### ISSUE TITLE
Find an API for for weather data

### ISSUE THREAD

**Issue by th0rgall** [osoc22/project-idlab#5]
Preferably one that already is queryable in RDF/linked data. Otherwise, use RML.io to convert!

**Comment by Matei9721** [comment]
I found this API which provides weather daily forecast for up to 16 days in future, or hourly forecast for up to 4 days in the future:
https://openweathermap.org/api/hourly-forecast

I will check if the API is free to use as it's not clear (they say 1000 request free per day). The return type is JSON.

**Comment by Matei9721** [comment]
I got a key, but it's not active. On their website, it says it can take a few hours.... Greeeat.

**Comment by Matei9721** [comment]
I will try by the end of today to take the JSON response from one of these and convert it to RDF using the RML.io
