### ISSUE TITLE
Unauthorized access to RETRIEVE/CREATE SolidDataSet when using a third-party pod provider

### ISSUE THREAD

**Issue by Matei9721** [osoc22/project-idlab#53]
Encountered this issue testing CRUD operations using the inrupt solid-client API.  We are getting a 401 Unauthorized access from the server.

![image](https://user-images.githubusercontent.com/60573633/179730393-8a888421-5347-41c3-9ec5-a0d2955b286c.png)

**Comment by Matei9721** [comment]
Added solution in #68 where the webID field has been removed and substituted with location storage field.

**Comment by Denperidge** [comment]
Fixed thanks to #68 merge!
