### ISSUE TITLE
Convert JSON weather response to RDF

### ISSUE THREAD

**Issue by Matei9721** [osoc22/project-idlab#6]
I will try to use the RML.io (https://rml.io/) to convert the response that we got from our JSON API(s )to RDF in order to add it to the Solid pod we have running.

**Comment by Denperidge** [comment]
I think that's not even needed! [While you can parse RDF into a dataset](https://docs.inrupt.com/developer-tools/api/javascript/solid-client/modules/rdfjs.html), it can also just [be built from javascript](https://docs.inrupt.com/developer-tools/javascript/client-libraries/tutorial/read-write-data/#write-data).

**Comment by Matei9721** [comment]
Bell will help us set up a proxy server that can more easily convert the JSON to RDF.

**Comment by Matei9721** [comment]
Proceeded with implementing a Fastify server that can convert and serve JSON-LD weather objects to the frontend.

- [ ]  Set up Fastify
- [ ] Convert city name to lang and long
- [ ] Pre-process data (as little as needed)
- [ ] Integrate the RmlMapper wrapper with the backend
- [ ] Generate RML mapping configuration file
- [ ] Set up Docker file
