### ISSUE TITLE
Mock weather data for Hackathon

### ISSUE THREAD

**Issue by Matei9721** [osoc22/project-idlab#8]
I will try to model some mock data for the demo application we are working on for the Hackathon. I am modeling it directly in JSON-LD such that we can convert it to Turtle or any other linked data format easily.

- [x] Have mock data in JSON-LD and Turtle form.
- [ ] Upload the data to Solid Pod.
- [ ] Query the data from the Pod.

**Comment by DemianD** [comment]
Closing in favor of #6
